//
//  Constants.h
//  QWCore_ios
//
//  Created by Monideep Purkayastha on 10/09/15.
//  Copyright (c) 2015 LivQuik. All rights reserved.
//

#import <Foundation/Foundation.h>

// POSSIBLE CONFIGURATIONS
FOUNDATION_EXPORT NSString * const CONFIG_LIVE;
FOUNDATION_EXPORT NSString * const CONFIG_UAT;
FOUNDATION_EXPORT NSString * const CONFIG_DEV;
FOUNDATION_EXPORT NSString * const CONFIG_STAGING ;
FOUNDATION_EXPORT NSString * const CONFIG_TEST;

//RELEASE STRING
FOUNDATION_EXPORT NSString * const SDK_VERSION;

// AJAX STUFF
FOUNDATION_EXPORT NSString * const SERVER_URL_LIVE;
FOUNDATION_EXPORT NSString * const SERVER_URL_UAT;
FOUNDATION_EXPORT NSString * const SERVER_URL_DEV;
FOUNDATION_EXPORT NSString * const SERVER_URL_DEV;
FOUNDATION_EXPORT NSString * const SERVER_URL_STAGING;
FOUNDATION_EXPORT NSString * const SERVER_URL_TEST;
FOUNDATION_EXPORT NSString * const SERVER_PORT_DEV;
FOUNDATION_EXPORT NSString * const ENDPOINT_PREFIX;
FOUNDATION_EXPORT NSString * const ENDPOINT_ZAGGLE_PREFIX;
FOUNDATION_EXPORT NSString * const ENDPOINT_POS_PREFIX;
FOUNDATION_EXPORT NSString * const TYPE_POST;
FOUNDATION_EXPORT NSString * const TYPE_GET;
FOUNDATION_EXPORT NSString * const STATUS_SUCCESS;
FOUNDATION_EXPORT NSString * const STATUS_FAILED;

// AJAX ENDPOINTS

// Cards API Endpoints
FOUNDATION_EXPORT NSString * const ENDPOINT_CARDS;
FOUNDATION_EXPORT NSString * const ENDPOINT_ADDCARD;
FOUNDATION_EXPORT NSString * const ENDPOINT_DELETE_CARD;
FOUNDATION_EXPORT NSString * const ENDPOINT_CHANGE_DEFAULT_CARD;

//  Payments API Endpoints
FOUNDATION_EXPORT NSString * const ENDPOINT_GETREQUESTEDPAYMENT;
FOUNDATION_EXPORT NSString * const ENDPOINT_REJECTPAYMENTS;
FOUNDATION_EXPORT NSString * const ENDPOINT_CANCELPAYMENT;
FOUNDATION_EXPORT NSString * const ENDPOINT_DROPPAYMENT;
FOUNDATION_EXPORT NSString * const ENDPOINT_RECHARGE;

FOUNDATION_EXPORT NSString * const ENDPOINT_HOWTOPAY;
FOUNDATION_EXPORT NSString * const ENDPOINT_HOWYOUPAID;
FOUNDATION_EXPORT NSString * const ENDPOINT_TRANSACTION_DETAILS;
FOUNDATION_EXPORT NSString * const ENDPOINT_TRANSACTION_HISTORY;
FOUNDATION_EXPORT NSString * const ENDPOINT_PAY;
FOUNDATION_EXPORT NSString * const ENDPOINT_REQUEST_PAYMENT;
FOUNDATION_EXPORT NSString * const ENDPOINT_PAYMENT;
FOUNDATION_EXPORT NSString * const ENDPOINT_REQUESTBILL;
FOUNDATION_EXPORT NSString * const ENDPOINT_PENDING_PAYMENTS;

// Places API Endpoints
FOUNDATION_EXPORT NSString * const ENDPOINT_PLACES;
FOUNDATION_EXPORT NSString * const ENDPOINT_REPORT_ISSUE;
FOUNDATION_EXPORT NSString * const ENDPOINT_CHECKIN;
FOUNDATION_EXPORT NSString * const ENDPOINT_CHECKOUT;
FOUNDATION_EXPORT NSString * const ENDPOINT_FEEDBACK;

// ERRORS
FOUNDATION_EXPORT NSString *const QWErrorMessageKey;
FOUNDATION_EXPORT NSString *const QWDomain;

#define QWJSONParsingErrorKey NSLocalizedString(@"The response from QuikWallet failed to get parsed into valid JSON.", nil)
#define QWUnexpectedError NSLocalizedString(@"There was an error processing your request.", @"Unexpected error")

// ERROR CODES
typedef NS_ENUM(NSInteger, QWErrorCode) {
    QWAPIError = 50, // General purpose API error
    QWConnectionError = 10 // Trouble connecting to QuikWallet
};


@interface Constants : NSObject

@end
